# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 00:12
from __future__ import unicode_literals

import cointrol.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171102_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='open',
            field=cointrol.core.fields.PriceField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
