# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 22:42
from __future__ import unicode_literals

import cointrol.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticker_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='eur_available',
            field=cointrol.core.fields.AmountField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='balance',
            name='eur_balance',
            field=cointrol.core.fields.AmountField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='balance',
            name='eur_reserved',
            field=cointrol.core.fields.AmountField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='balance',
            name='xrp_available',
            field=cointrol.core.fields.AmountField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='balance',
            name='xrp_balance',
            field=cointrol.core.fields.AmountField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='balance',
            name='xrp_reserved',
            field=cointrol.core.fields.AmountField(decimal_places=8, default=0, max_digits=30),
        ),
    ]
